### ISSUE TITLE
[question] How do I add a theme?

### ISSUE THREAD

**Issue by fredguth** [spences10/sveltekit-theme-switch#150]
I guess it is using daisyui.themes to get theme data.  Because if I change it in the tailwind.config.cjs...

```js
daisyui: {
  themes: [{
    mytheme: {
      "primary": "#334477",
      "secondary": "#0077CC",
...
```
it only shows mytheme in the buttons and the select does not work.

How do I add mytheme?

**Comment by spences10** [comment]
Hey @fredguth if you check out the daisyUI documentation there's a great [section] in there for creating your own themes.

Hope that helps 👍

[section]: https://daisyui.com/docs/themes/#-4
